version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/jsonplaceholder?schema=public
      JWT_SECRET: your-super-secret-key-here
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsonplaceholder
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: 